dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

install:
  - pip install -r requirements.txt

script:
  - pylint unification/ tests/
  - if [[ `command -v black` ]]; then
      black --check unification tests;
    fi
  - pytest -v tests/ --benchmark-skip --cov=unification/
  - pytest -v tests/ --benchmark-only --benchmark-autosave --benchmark-group-by=group,param:size --benchmark-max-time=3

after_success:
  - coveralls
