sudo: false
language: python
python:
  - "3.6"
  - "pypy3"
matrix:
  include:
    - python: 3.7
      dist: xenial
install: pip install tox-travis
script: tox
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then pip install coveralls ; coveralls ; fi
notifications:
  email: false
