dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

install:
  - pip install -r requirements.txt

script:
  - pylint unification/ tests/
  - if [[ `command -v black` ]]; then
      black --check unification tests;
    fi
  - pytest -v tests/ --cov=unification/

after_success:
  - coveralls
